name: Scheduled Automerge Master -> Staging -> Develop

on:
  schedule:
    - cron: '0 0 * * 1-5' # At 00:00, Monday through Friday
  workflow_dispatch: # on button click

jobs:
  merge-master-to-staging:
    name: Merge Master to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "Sofie-Automation@users.noreply.github.com"
          git config --local user.name "GitHub Actions # Sofie-Automation"
      - name: Merge 'master' to 'staging'
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/master -m "Automerge 'master' to 'staging'"
          git push

  merge-staging-to-develop:
    name: Merge Staging to Develop
    runs-on: ubuntu-latest
    needs: merge-master-to-staging
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "Sofie-Automation@users.noreply.github.com"
          git config --local user.name "GitHub Actions # Sofie-Automation"
      - name: Merge 'staging' to 'develop'
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/staging -m "Automerge 'staging' to 'develop'."
          git push

