name: Scheduled Automerge Staging -> Develop

on:
  schedule:
    - cron: '15 0 * * 1-5' # At 00:15, Monday through Friday
  workflow_dispatch: # on button click

jobs:
  merge-staging-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "Sofie-Automation@users.noreply.github.com"
          git config --local user.name "GitHub Actions # Sofie-Automation"
      - name: Merge 'staging' to 'develop'
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/staging -m "Automerge 'staging' to 'develop'."
          git push
