name: "Prune docker images"

on:
  workflow_dispatch:

jobs:
  prune-docker-images:
    uses: nrkno/sofie-github-workflows/.github/workflows/prune-docker-images.yml@main
    strategy:
      max-parallel: 1
      matrix:
        repo: [ server-core, playout-gateway, mos-gateway ]
    with:
      dry-run: false
      prune-untagged: true
      package-name: sofie-core-${{ matrix.repo }}
    secrets:
      prune-token: ${{ secrets.GHCR_PRUNE_TOKEN }}
